//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.MtaSts.PolicyFetcher.Parsing {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Explanations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Explanations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.MtaSts.PolicyFetcher.Parsing.Explanations", typeof(Explanations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string VersionKeyValidExplanation {
            get {
                return ResourceManager.GetString("VersionKeyValidExplanation", resourceCulture);
            }
        }
        
        internal static string VersionKeyInvalidExplanation {
            get {
                return ResourceManager.GetString("VersionKeyInvalidExplanation", resourceCulture);
            }
        }
        
        internal static string ModeKeyEnforceExplanation {
            get {
                return ResourceManager.GetString("ModeKeyEnforceExplanation", resourceCulture);
            }
        }
        
        internal static string ModeKeyTestingExplanation {
            get {
                return ResourceManager.GetString("ModeKeyTestingExplanation", resourceCulture);
            }
        }
        
        internal static string ModeKeyNoneExplanation {
            get {
                return ResourceManager.GetString("ModeKeyNoneExplanation", resourceCulture);
            }
        }
        
        internal static string ModeKeyInvalidExplanation {
            get {
                return ResourceManager.GetString("ModeKeyInvalidExplanation", resourceCulture);
            }
        }
        
        internal static string MaxAgeKeyValidExplanation {
            get {
                return ResourceManager.GetString("MaxAgeKeyValidExplanation", resourceCulture);
            }
        }
        
        internal static string MaxAgeKeyInvalidValidExplanation {
            get {
                return ResourceManager.GetString("MaxAgeKeyInvalidValidExplanation", resourceCulture);
            }
        }
        
        internal static string MxKeyValidExplanation {
            get {
                return ResourceManager.GetString("MxKeyValidExplanation", resourceCulture);
            }
        }
        
        internal static string MxKeyInvalidExplanation {
            get {
                return ResourceManager.GetString("MxKeyInvalidExplanation", resourceCulture);
            }
        }
    }
}
