//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.MtaSts.PolicyFetcher.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MtaStsRulesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MtaStsRulesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.MtaSts.PolicyFetcher.Rules.MtaStsRulesResource", typeof(MtaStsRulesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MX patterns were found in your policy file..
        /// </summary>
        internal static string NoMxPresent {
            get {
                return ResourceManager.GetString("NoMxPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTA-STS policy max_age value is too short (less than 2 weeks). We recommend a longer cache period to protect against sustained attacks..
        /// </summary>
        internal static string PolicyMaxAgeIsTooShortEnforceMode {
            get {
                return ResourceManager.GetString("PolicyMaxAgeIsTooShortEnforceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTA-STS policy max_age value is too short (less than 86400)..
        /// </summary>
        internal static string PolicyMaxAgeIsTooShortTestingMode {
            get {
                return ResourceManager.GetString("PolicyMaxAgeIsTooShortTestingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak MTA-STS policy. TLS email encryption is vulnerable to downgrade attacks. Next step: work towards an MTA-STS ‘enforce’ policy..
        /// </summary>
        internal static string PolicyNotEnforced {
            get {
                return ResourceManager.GetString("PolicyNotEnforced", resourceCulture);
            }
        }
    }
}
