//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.MtaSts.PolicyFetcher.Rules {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MtaStsRulesMarkDownResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MtaStsRulesMarkDownResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.MtaSts.PolicyFetcher.Rules.MtaStsRulesMarkDownResource", typeof(MtaStsRulesMarkDownResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PolicyMaxAgeIsTooShortEnforceMode {
            get {
                return ResourceManager.GetString("PolicyMaxAgeIsTooShortEnforceMode", resourceCulture);
            }
        }
        
        internal static string PolicyMaxAgeIsTooShortTestingMode {
            get {
                return ResourceManager.GetString("PolicyMaxAgeIsTooShortTestingMode", resourceCulture);
            }
        }
        
        internal static string PolicyNotEnforced {
            get {
                return ResourceManager.GetString("PolicyNotEnforced", resourceCulture);
            }
        }
        
        internal static string NoMxPresent {
            get {
                return ResourceManager.GetString("NoMxPresent", resourceCulture);
            }
        }
    }
}
