//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.MtaSts.PolicyFetcher.Domain.Errors {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.MtaSts.PolicyFetcher.Domain.Errors.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PolicyParseError {
            get {
                return ResourceManager.GetString("PolicyParseError", resourceCulture);
            }
        }
        
        internal static string PolicyParseErrorMarkdown {
            get {
                return ResourceManager.GetString("PolicyParseErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string KeyValueErrorMarkdown {
            get {
                return ResourceManager.GetString("KeyValueErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string ModeKeyErrorMarkdown {
            get {
                return ResourceManager.GetString("ModeKeyErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string MxKeyErrorMarkdown {
            get {
                return ResourceManager.GetString("MxKeyErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string MaxAgeKeyErrorMarkdown {
            get {
                return ResourceManager.GetString("MaxAgeKeyErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string VersionKeyErrorMarkdown {
            get {
                return ResourceManager.GetString("VersionKeyErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string MaxOccurrencesExceededError {
            get {
                return ResourceManager.GetString("MaxOccurrencesExceededError", resourceCulture);
            }
        }
        
        internal static string FetchTimeOutMarkdown {
            get {
                return ResourceManager.GetString("FetchTimeOutMarkdown", resourceCulture);
            }
        }
    }
}
